[project]
name = "quant-forge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "cloudscraper>=1.2.71",
    "finance-data",
    "pydantic>=2.12.4",
]
authors = [{ name = "metbatgui", email = "metbatguidev@gmail.com" }]

[tool.uv.workspace]
members = [
    "libs/finance_data",
    "libs/krx_netbuy_crawler",
    "dart-fss-extractor",
]

[tool.uv.sources]
finance-data = { workspace = true }
krx-netbuy-crawler = { workspace = true }
